/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_kostromdan_mods_crash_assistant_app_utils_gpu_DirectXGPUDetector */

#ifndef _Included_dev_kostromdan_mods_crash_assistant_app_utils_gpu_DirectXGPUDetector
#define _Included_dev_kostromdan_mods_crash_assistant_app_utils_gpu_DirectXGPUDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_kostromdan_mods_crash_assistant_app_utils_gpu_DirectXGPUDetector
 * Method:    getSerialisedGPUs
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_kostromdan_mods_crash_1assistant_app_utils_gpu_DirectXGPUDetector_getSerialisedGPUs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
